[package]
name = "gr-engine"
version = "0.1.0"
authors = ["Bartłomiej Kamiński <fizyk20@gmail.com>"]

[lib]
name = "gr_engine"

[dependencies]
differential-geometry = "0.2.2"
generic-array = "0.12"
numeric-algs = "0.2.1"
